# Generated by Django 6.0.3 on 2026-03-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'managed': False},
        ),
    ]
