# Generated by Django 6.0.3 on 2026-03-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_slot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
    ]
