# Generated by Django 6.0.3 on 2026-03-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_slot_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slot',
            table='booking_slot',
        ),
    ]
